version: '3.1'
volumes:
  mongodb_data:

services:
  mongodb:
      container_name: mongodb
      image: mongo:focal
      volumes:
        - mongodb_data:/data/db
      ports:
        - 27017:27017
      restart: always
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
